name: Semanticore

on:
  push:
    branches:
      - main
jobs:
  semanticore:
    runs-on: ubuntu-latest
    name: Semanticore
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.*
      - name: Semanticore
        run: go run github.com/aoepeople/semanticore@v0 -npm-update-version package.json
        env:
          SEMANTICORE_TOKEN: ${{secrets.GITHUB_TOKEN}}
